query getAllArticles {
  articles {
    id
    title
    author
    date
    is_release
    image {
      url
    }
  }
}

query getArticle($id: ID!) {
  article(id: $id) {
    id
    title
    author
    date
    content
    is_release
    image {
      url
    }
    comments {
      id
      name
      message
    }
  }
}
