query getAllArticles {
  articles {
    id
    title
    author
    date
    is_release
    image {
      url
    }
  }
}

query getArticle($id: ID!) {
  article(id: $id) {
    id
    title
    author
    date
    content
    is_release
    image {
      url
    }
    comments {
      id
      name
      message
    }
  }
}

mutation createArticle(
  $title: String,
  $date: DateTime,
	$author: String,
	$is_release: Boolean,
	$content: String,
	$image: ID) {
  createArticle(input: {
    data: {
      title: $title,
      date: $date,
      author: $author,
      is_release: $is_release,
      content: $content,
      image: $image
    }
  }) {
    article {
      id
    }
  }
}
